/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface Apikey {
  configId: string;
  createdAt: string;
  enabled: number | null;
  expiresAt: string | null;
  id: string;
  key: string;
  lastRefillAt: string | null;
  lastRequest: string | null;
  metadata: string | null;
  name: string | null;
  permissions: string | null;
  prefix: string | null;
  rateLimitEnabled: number | null;
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  referenceId: string;
  refillAmount: number | null;
  refillInterval: number | null;
  remaining: number | null;
  requestCount: number | null;
  start: string | null;
  updatedAt: string;
}

export interface Invitation {
  createdAt: string;
  email: string;
  expiresAt: string;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Member {
  createdAt: string;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Organization {
  createdAt: string;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
  stripeCustomerId: string | null;
}

export interface Project {
  createdAt: string;
  createdBy: string | null;
  description: string | null;
  id: string;
  name: string;
  organizationId: string;
  updatedAt: string;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: string;
  expiresAt: string;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface Subscription {
  billingInterval: string | null;
  cancelAt: string | null;
  cancelAtPeriodEnd: number | null;
  canceledAt: string | null;
  endedAt: string | null;
  id: string;
  periodEnd: string | null;
  periodStart: string | null;
  plan: string;
  referenceId: string;
  seats: number | null;
  status: string;
  stripeCustomerId: string | null;
  stripeScheduleId: string | null;
  stripeSubscriptionId: string | null;
  trialEnd: string | null;
  trialStart: string | null;
}

export interface User {
  banExpires: string | null;
  banned: Generated<number | null>;
  banReason: string | null;
  createdAt: string;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  stripeCustomerId: string | null;
  updatedAt: string;
}

export interface Verification {
  createdAt: string;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string;
  value: string;
}

export interface DB {
  account: Account;
  apikey: Apikey;
  invitation: Invitation;
  member: Member;
  organization: Organization;
  project: Project;
  session: Session;
  subscription: Subscription;
  user: User;
  verification: Verification;
}
