/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppAuthedRouteImport } from './routes/app/_authed'
import { Route as AppForgotPasswordRouteImport } from './routes/app/forgot-password'
import { Route as AppResetPasswordRouteImport } from './routes/app/reset-password'
import { Route as AppSignInRouteImport } from './routes/app/sign-in'
import { Route as AppSignUpRouteImport } from './routes/app/sign-up'
import { Route as AppAuthedOrgRouteImport } from './routes/app/_authed/_org'
import { Route as AppAuthedAcceptInvitationRouteImport } from './routes/app/_authed/accept-invitation'
import { Route as AppAuthedOperatorRouteImport } from './routes/app/_authed/operator'
import { Route as AppAuthedWelcomeRouteImport } from './routes/app/_authed/welcome'
import { Route as AppAuthedOrgIndexRouteImport } from './routes/app/_authed/_org/index'
import { Route as AppAuthedOrgBillingRouteImport } from './routes/app/_authed/_org/billing'
import { Route as AppAuthedOrgKeysRouteImport } from './routes/app/_authed/_org/keys'
import { Route as AppAuthedOrgMembersRouteImport } from './routes/app/_authed/_org/members'
import { Route as AppAuthedOrgSettingsRouteImport } from './routes/app/_authed/_org/settings'
import { Route as AppAuthedOrgProjectsIndexRouteImport } from './routes/app/_authed/_org/projects/index'
import { Route as AppAuthedOrgProjectsProjectIdRouteImport } from './routes/app/_authed/_org/projects/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResetPasswordRoute = AppResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignInRoute = AppSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignUpRoute = AppSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthedOrgRoute = AppAuthedOrgRouteImport.update({
  id: '/_org',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedAcceptInvitationRoute =
  AppAuthedAcceptInvitationRouteImport.update({
    id: '/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedOperatorRoute = AppAuthedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedWelcomeRoute = AppAuthedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedOrgIndexRoute = AppAuthedOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedOrgRoute,
} as any)
const AppAuthedOrgBillingRoute = AppAuthedOrgBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppAuthedOrgRoute,
} as any)
const AppAuthedOrgKeysRoute = AppAuthedOrgKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppAuthedOrgRoute,
} as any)
const AppAuthedOrgMembersRoute = AppAuthedOrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAuthedOrgRoute,
} as any)
const AppAuthedOrgSettingsRoute = AppAuthedOrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAuthedOrgRoute,
} as any)
const AppAuthedOrgProjectsIndexRoute =
  AppAuthedOrgProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppAuthedOrgRoute,
  } as any)
const AppAuthedOrgProjectsProjectIdRoute =
  AppAuthedOrgProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppAuthedOrgRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/sign-in': typeof AppSignInRoute
  '/app/sign-up': typeof AppSignUpRoute
  '/app/accept-invitation': typeof AppAuthedAcceptInvitationRoute
  '/app/operator': typeof AppAuthedOperatorRoute
  '/app/welcome': typeof AppAuthedWelcomeRoute
  '/app/billing': typeof AppAuthedOrgBillingRoute
  '/app/keys': typeof AppAuthedOrgKeysRoute
  '/app/members': typeof AppAuthedOrgMembersRoute
  '/app/settings': typeof AppAuthedOrgSettingsRoute
  '/app/': typeof AppAuthedOrgIndexRoute
  '/app/projects/$projectId': typeof AppAuthedOrgProjectsProjectIdRoute
  '/app/projects/': typeof AppAuthedOrgProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAuthedOrgIndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/sign-in': typeof AppSignInRoute
  '/app/sign-up': typeof AppSignUpRoute
  '/app/accept-invitation': typeof AppAuthedAcceptInvitationRoute
  '/app/operator': typeof AppAuthedOperatorRoute
  '/app/welcome': typeof AppAuthedWelcomeRoute
  '/app/billing': typeof AppAuthedOrgBillingRoute
  '/app/keys': typeof AppAuthedOrgKeysRoute
  '/app/members': typeof AppAuthedOrgMembersRoute
  '/app/settings': typeof AppAuthedOrgSettingsRoute
  '/app/projects/$projectId': typeof AppAuthedOrgProjectsProjectIdRoute
  '/app/projects': typeof AppAuthedOrgProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/_authed': typeof AppAuthedRouteWithChildren
  '/app/forgot-password': typeof AppForgotPasswordRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/sign-in': typeof AppSignInRoute
  '/app/sign-up': typeof AppSignUpRoute
  '/app/_authed/_org': typeof AppAuthedOrgRouteWithChildren
  '/app/_authed/accept-invitation': typeof AppAuthedAcceptInvitationRoute
  '/app/_authed/operator': typeof AppAuthedOperatorRoute
  '/app/_authed/welcome': typeof AppAuthedWelcomeRoute
  '/app/_authed/_org/billing': typeof AppAuthedOrgBillingRoute
  '/app/_authed/_org/keys': typeof AppAuthedOrgKeysRoute
  '/app/_authed/_org/members': typeof AppAuthedOrgMembersRoute
  '/app/_authed/_org/settings': typeof AppAuthedOrgSettingsRoute
  '/app/_authed/_org/': typeof AppAuthedOrgIndexRoute
  '/app/_authed/_org/projects/$projectId': typeof AppAuthedOrgProjectsProjectIdRoute
  '/app/_authed/_org/projects/': typeof AppAuthedOrgProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/app/forgot-password'
    | '/app/reset-password'
    | '/app/sign-in'
    | '/app/sign-up'
    | '/app/accept-invitation'
    | '/app/operator'
    | '/app/welcome'
    | '/app/billing'
    | '/app/keys'
    | '/app/members'
    | '/app/settings'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/app/forgot-password'
    | '/app/reset-password'
    | '/app/sign-in'
    | '/app/sign-up'
    | '/app/accept-invitation'
    | '/app/operator'
    | '/app/welcome'
    | '/app/billing'
    | '/app/keys'
    | '/app/members'
    | '/app/settings'
    | '/app/projects/$projectId'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/privacy'
    | '/terms'
    | '/app/_authed'
    | '/app/forgot-password'
    | '/app/reset-password'
    | '/app/sign-in'
    | '/app/sign-up'
    | '/app/_authed/_org'
    | '/app/_authed/accept-invitation'
    | '/app/_authed/operator'
    | '/app/_authed/welcome'
    | '/app/_authed/_org/billing'
    | '/app/_authed/_org/keys'
    | '/app/_authed/_org/members'
    | '/app/_authed/_org/settings'
    | '/app/_authed/_org/'
    | '/app/_authed/_org/projects/$projectId'
    | '/app/_authed/_org/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/forgot-password': {
      id: '/app/forgot-password'
      path: '/forgot-password'
      fullPath: '/app/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reset-password': {
      id: '/app/reset-password'
      path: '/reset-password'
      fullPath: '/app/reset-password'
      preLoaderRoute: typeof AppResetPasswordRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sign-in': {
      id: '/app/sign-in'
      path: '/sign-in'
      fullPath: '/app/sign-in'
      preLoaderRoute: typeof AppSignInRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sign-up': {
      id: '/app/sign-up'
      path: '/sign-up'
      fullPath: '/app/sign-up'
      preLoaderRoute: typeof AppSignUpRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_authed/_org': {
      id: '/app/_authed/_org'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedOrgRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/accept-invitation': {
      id: '/app/_authed/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/app/accept-invitation'
      preLoaderRoute: typeof AppAuthedAcceptInvitationRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/operator': {
      id: '/app/_authed/operator'
      path: '/operator'
      fullPath: '/app/operator'
      preLoaderRoute: typeof AppAuthedOperatorRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/welcome': {
      id: '/app/_authed/welcome'
      path: '/welcome'
      fullPath: '/app/welcome'
      preLoaderRoute: typeof AppAuthedWelcomeRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/app/_authed/_org/': {
      id: '/app/_authed/_org/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedOrgIndexRouteImport
      parentRoute: typeof AppAuthedOrgRoute
    }
    '/app/_authed/_org/billing': {
      id: '/app/_authed/_org/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppAuthedOrgBillingRouteImport
      parentRoute: typeof AppAuthedOrgRoute
    }
    '/app/_authed/_org/keys': {
      id: '/app/_authed/_org/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppAuthedOrgKeysRouteImport
      parentRoute: typeof AppAuthedOrgRoute
    }
    '/app/_authed/_org/members': {
      id: '/app/_authed/_org/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppAuthedOrgMembersRouteImport
      parentRoute: typeof AppAuthedOrgRoute
    }
    '/app/_authed/_org/settings': {
      id: '/app/_authed/_org/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAuthedOrgSettingsRouteImport
      parentRoute: typeof AppAuthedOrgRoute
    }
    '/app/_authed/_org/projects/': {
      id: '/app/_authed/_org/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppAuthedOrgProjectsIndexRouteImport
      parentRoute: typeof AppAuthedOrgRoute
    }
    '/app/_authed/_org/projects/$projectId': {
      id: '/app/_authed/_org/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppAuthedOrgProjectsProjectIdRouteImport
      parentRoute: typeof AppAuthedOrgRoute
    }
  }
}

interface AppAuthedOrgRouteChildren {
  AppAuthedOrgBillingRoute: typeof AppAuthedOrgBillingRoute
  AppAuthedOrgKeysRoute: typeof AppAuthedOrgKeysRoute
  AppAuthedOrgMembersRoute: typeof AppAuthedOrgMembersRoute
  AppAuthedOrgSettingsRoute: typeof AppAuthedOrgSettingsRoute
  AppAuthedOrgIndexRoute: typeof AppAuthedOrgIndexRoute
  AppAuthedOrgProjectsProjectIdRoute: typeof AppAuthedOrgProjectsProjectIdRoute
  AppAuthedOrgProjectsIndexRoute: typeof AppAuthedOrgProjectsIndexRoute
}

const AppAuthedOrgRouteChildren: AppAuthedOrgRouteChildren = {
  AppAuthedOrgBillingRoute: AppAuthedOrgBillingRoute,
  AppAuthedOrgKeysRoute: AppAuthedOrgKeysRoute,
  AppAuthedOrgMembersRoute: AppAuthedOrgMembersRoute,
  AppAuthedOrgSettingsRoute: AppAuthedOrgSettingsRoute,
  AppAuthedOrgIndexRoute: AppAuthedOrgIndexRoute,
  AppAuthedOrgProjectsProjectIdRoute: AppAuthedOrgProjectsProjectIdRoute,
  AppAuthedOrgProjectsIndexRoute: AppAuthedOrgProjectsIndexRoute,
}

const AppAuthedOrgRouteWithChildren = AppAuthedOrgRoute._addFileChildren(
  AppAuthedOrgRouteChildren,
)

interface AppAuthedRouteChildren {
  AppAuthedOrgRoute: typeof AppAuthedOrgRouteWithChildren
  AppAuthedAcceptInvitationRoute: typeof AppAuthedAcceptInvitationRoute
  AppAuthedOperatorRoute: typeof AppAuthedOperatorRoute
  AppAuthedWelcomeRoute: typeof AppAuthedWelcomeRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedOrgRoute: AppAuthedOrgRouteWithChildren,
  AppAuthedAcceptInvitationRoute: AppAuthedAcceptInvitationRoute,
  AppAuthedOperatorRoute: AppAuthedOperatorRoute,
  AppAuthedWelcomeRoute: AppAuthedWelcomeRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppResetPasswordRoute: typeof AppResetPasswordRoute
  AppSignInRoute: typeof AppSignInRoute
  AppSignUpRoute: typeof AppSignUpRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppResetPasswordRoute: AppResetPasswordRoute,
  AppSignInRoute: AppSignInRoute,
  AppSignUpRoute: AppSignUpRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
